# Generated by Django 2.2.24 on 2021-11-25 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=300, null=True)),
                ('target', models.PositiveIntegerField()),
                ('frequency', models.PositiveIntegerField()),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admins', models.ManyToManyField(related_name='newsletters_editors', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletters_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionsNewsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('newsletter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsletters_app.Newsletter')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='newsletter',
            name='subs',
            field=models.ManyToManyField(through='newsletters_app.SubscriptionsNewsletter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='tags',
            field=models.ManyToManyField(related_name='newsletters_tagged', to='tags.Tag'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='votes',
            field=models.ManyToManyField(related_name='Votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='subscriptionsnewsletter',
            constraint=models.UniqueConstraint(fields=('user', 'newsletter'), name='unique_user_subscription'),
        ),
    ]
