# Generated by Django 2.2.24 on 2021-11-27 22:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='subs',
            field=models.ManyToManyField(blank=True, through='newsletters_app.SubscriptionsNewsletter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='Votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
