# Generated by Django 2.2.24 on 2021-11-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('slug', models.SlugField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
